[package]
name = "workarounds"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
zsh-module = { path = "../../zsh-module" }
